# Generated by Django 6.0 on 2026-01-03 20:22

import django.db.models.deletion
import uuid
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=videos.models.video_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.BigIntegerField(default=0)),
                ('duration', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('safe', 'Safe'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('sensitivity_score', models.FloatField(default=0.0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
